Repository BBOMI-With-Children/AlarmApp, pull requests merged in 2025-08, with the labels that each got.

#6 chore: 찐 수정 완료
  .github/ISSUE_TEMPLATE/add_request.yml
  .github/ISSUE_TEMPLATE/chore_request.yml
  .github/ISSUE_TEMPLATE/doc_request.yml
  .github/ISSUE_TEMPLATE/feat_request.yml
  .github/ISSUE_TEMPLATE/fix_request.yml
  .github/ISSUE_TEMPLATE/perf_request.yml
  .github/ISSUE_TEMPLATE/refactor_request.yml
  Alarm.xcodeproj/project.pbxproj
  Alarm.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Alarm/.editorconfig
  Alarm/App/AppDelegate.swift
  Alarm/App/SceneDelegate.swift
  Alarm/Scenes/Alarm/AlarmViewController.swift
  Alarm/Scenes/RootScene/MainTabBarController.swift
  Alarm/Scenes/Stopwatch/StopwatchViewController.swift
  Alarm/Scenes/Timer/TimerViewController.swift
  Alarm/Scenes/World/WorldViewController.swift
Labels: chore

#7 Develop
  .github/ISSUE_TEMPLATE/add_request.yml
  .github/ISSUE_TEMPLATE/chore_request.yml
  .github/ISSUE_TEMPLATE/doc_request.yml
  .github/ISSUE_TEMPLATE/feat_request.yml
  .github/ISSUE_TEMPLATE/fix_request.yml
  .github/ISSUE_TEMPLATE/perf_request.yml
  .github/ISSUE_TEMPLATE/refactor_request.yml
  Alarm.xcodeproj/project.pbxproj
  Alarm.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Alarm/.editorconfig
  Alarm/App/AppDelegate.swift
  Alarm/App/SceneDelegate.swift
  Alarm/Scenes/Alarm/AlarmViewController.swift
  Alarm/Scenes/RootScene/MainTabBarController.swift
  Alarm/Scenes/Stopwatch/StopwatchViewController.swift
  Alarm/Scenes/Timer/TimerViewController.swift
  Alarm/Scenes/World/WorldViewController.swift
Labels: chore

#10 Develop
  .github/ISSUE_TEMPLATE/add_request.yml
  .github/ISSUE_TEMPLATE/chore_request.yml
  .github/ISSUE_TEMPLATE/doc_request.yml
  .github/ISSUE_TEMPLATE/feat_request.yml
  .github/ISSUE_TEMPLATE/fix_request.yml
  .github/ISSUE_TEMPLATE/perf_request.yml
  .github/ISSUE_TEMPLATE/refactor_request.yml
Labels: chore

#13 Develop
  .github/ISSUE_TEMPLATE/add_request.yml
  .github/ISSUE_TEMPLATE/chore_request.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc_request.yml
  .github/ISSUE_TEMPLATE/feat_request.yml
  .github/ISSUE_TEMPLATE/fix_request.yml
  .github/ISSUE_TEMPLATE/perf_request.yml
  .github/ISSUE_TEMPLATE/refactor_request.yml
Labels: chore

#16 Develop
  .github/ISSUE_TEMPLATE/add_request.yml
  .github/ISSUE_TEMPLATE/chore_request.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs_request.yml
  .github/ISSUE_TEMPLATE/feat_request.yml
  .github/ISSUE_TEMPLATE/refactor_request.yml
Labels: chore

#32 타이머 데이터 등록 및 테이블 뷰에 표시
  Alarm/Scenes/Timer/AddTimerViewController.swift
  Alarm/Scenes/Timer/TimerDataManager.swift
  Alarm/Scenes/Timer/TimerPickerView.swift
  Alarm/Scenes/Timer/TimerTableViewCell.swift
  Alarm/Scenes/Timer/TimerViewController.swift
Labels: add, feat

#37 Feat: #22 - 모델, 싱글톤 구현
  Alarm.xcodeproj/project.pbxproj
  Alarm/Scenes/Alarm/Alarm.swift
  Alarm/Scenes/Alarm/AlarmViewController.swift
  Alarm/Scenes/Service/AlarmManager.swift
Labels: feat

#39 feat: #35 - 스톱워치 lap time list 구현
  Alarm/Scenes/Stopwatch/StopWatchCircleView.swift
  Alarm/Scenes/Stopwatch/StopwatchViewController.swift
Labels: feat

#43 Feat: #29 - 편집, + 버튼 기능 구현, RxSwift 도입
  Alarm.xcodeproj/project.pbxproj
  Alarm/Scenes/Alarm/AlarmViewController.swift
  Alarm/Scenes/Service/AlarmManager.swift
Labels: doc, feat

#44 Feat/timer feature
  Alarm/Scenes/Timer/AddTimerViewController.swift
  Alarm/Scenes/Timer/TimerDataManager.swift
  Alarm/Scenes/Timer/TimerTableViewCell.swift
  Alarm/Scenes/Timer/TimerViewController.swift
Labels: chore, feat

#58 도시 선택 Modal UI 및 기본 데이터 구현
  Alarm/Scenes/WorldTime/WorldTimeCell.swift
  Alarm/Scenes/WorldTime/WorldTimeCitySelectionViewController.swift
  Alarm/Scenes/WorldTime/WorldTimeCitySelectionViewModel.swift
  Alarm/Scenes/WorldTime/WorldTimeViewController.swift
Labels: feat

#56 feat: #51 - 스톱워치 랩타임 기능 구현
  Alarm/Scenes/Stopwatch/LapCollectionViewCell.swift
  Alarm/Scenes/Stopwatch/StopWatchModel.swift
  Alarm/Scenes/Stopwatch/StopWatchViewModel.swift
  Alarm/Scenes/Stopwatch/StopwatchViewController.swift
Labels: feat

#60 feat: #57 - 스톱워치 원형 UI 기능 구현
  Alarm/Scenes/Stopwatch/StopWatchCircleView.swift
  Alarm/Scenes/Stopwatch/StopWatchViewModel.swift
  Alarm/Scenes/Stopwatch/StopwatchViewController.swift
Labels: feat

#64 feat: #63 - 알람 페이지 셀 UI 구현
  Alarm/Scenes/Alarm/Alarm.swift
  Alarm/Scenes/Alarm/AlarmCell.swift
  Alarm/Scenes/Alarm/AlarmViewController.swift
Labels: feat

#68 feat: #67 - UserDefaults로 세계시계 저장/복원
  Alarm/Scenes/WorldTime/WorldTimeViewController.swift
  Alarm/Scenes/WorldTime/WorldTimeViewModel.swift
Labels: feat

#75 feat: #73 - 요일 선택 밑 셀 UI 구현
  Alarm/Scenes/Alarm/AlarmCell.swift
  Alarm/Scenes/AlarmEdit/AlarmEditViewController.swift
Labels: feat

#82 feat: #61 - 스톱워치 UserDefaults 적용
  Alarm/Scenes/Service/StopWatchUserDefaults.swift
  Alarm/Scenes/Stopwatch/StopWatchCircleView.swift
  Alarm/Scenes/Stopwatch/StopWatchModel.swift
  Alarm/Scenes/Stopwatch/StopWatchViewModel.swift
  Alarm/Scenes/Stopwatch/StopwatchViewController.swift
Labels: feat

#85 chore: #84 UserDefualts 오타 수정
  Alarm/Scenes/Stopwatch/StopWatchViewModel.swift
Labels: chore

#86 feat: #79 - 사운드, 배너 추가
  Alarm/App/AppDelegate.swift
  Alarm/Scenes/Alarm/Alarm.swift
  Alarm/Scenes/AlarmEdit/AlarmEditViewController.swift
  Alarm/Scenes/AlarmEdit/Weekday.swift
  Alarm/Scenes/AlarmEdit/WeekdaySelectorView.swift
Labels: chore, feat

#93 chore: #77 - 비활성화 상태일 땐 반투명으로
  Alarm/Scenes/Alarm/AlarmCell.swift
Labels: chore

#96 chore: #80 - 알람 켜져있을 때만 울리게, 파일 역할에 맞게 분리
  Alarm/Scenes/AlarmEdit/AlarmEditViewController.swift
  Alarm/Scenes/Service/AlarmManager.swift
Labels: chore

#103 feat: #98 - 삭제 버튼 구현, 알람 추가일 때는 비활성화
  Alarm/Scenes/Alarm/AlarmViewController.swift
  Alarm/Scenes/AlarmEdit/AlarmEditViewController.swift
Labels: feat

#107 chore: #106 - 글자 크기 수정
  Alarm/Scenes/Alarm/AlarmCell.swift
Labels: chore

#108 feat: 알람 앱 최종본 main 반영
  .editorconfig
  Alarm.xcodeproj/project.pbxproj
  Alarm/App/AppDelegate.swift
  Alarm/App/SceneDelegate.swift
  Alarm/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Alarm/Resources/Assets.xcassets/AppIcon.appiconset/icon.png
  Alarm/Resources/Assets.xcassets/backgroundColor.colorset/Contents.json
  Alarm/Resources/Assets.xcassets/mainColor.colorset/Contents.json
  Alarm/Resources/Assets.xcassets/modalColor.colorset/Contents.json
  Alarm/Resources/Assets.xcassets/sectionColor.colorset/Contents.json
  Alarm/Resources/radial.caf
  Alarm/Scenes/Alarm/Alarm.swift
  Alarm/Scenes/Alarm/AlarmCell.swift
  Alarm/Scenes/Alarm/AlarmViewController.swift
  Alarm/Scenes/AlarmEdit/AlarmEditViewController.swift
  Alarm/Scenes/AlarmEdit/Weekday.swift
  Alarm/Scenes/AlarmEdit/WeekdaySelectorView.swift
  Alarm/Scenes/RootScene/MainTabBarController.swift
  Alarm/Scenes/Service/AlarmManager.swift
  Alarm/Scenes/Service/StopWatchUserDefaults.swift
  Alarm/Scenes/Stopwatch/LapCollectionViewCell.swift
  Alarm/Scenes/Stopwatch/StopWatchCircleView.swift
  Alarm/Scenes/Stopwatch/StopWatchModel.swift
  Alarm/Scenes/Stopwatch/StopWatchViewModel.swift
  Alarm/Scenes/Stopwatch/StopwatchViewController.swift
  Alarm/Scenes/Timer/AddTimerViewController.swift
  Alarm/Scenes/Timer/TimerDataManager.swift
  Alarm/Scenes/Timer/TimerPickerView.swift
  Alarm/Scenes/Timer/TimerTableViewCell.swift
  Alarm/Scenes/Timer/TimerViewController.swift
  Alarm/Scenes/World/WorldViewController.swift
  Alarm/Scenes/WorldTime/CitySelection/WorldTimeCitySelectionViewController.swift
  Alarm/Scenes/WorldTime/CitySelection/WorldTimeCitySelectionViewModel.swift
  Alarm/Scenes/WorldTime/WorldTime/WorldTimeCell.swift
  Alarm/Scenes/WorldTime/WorldTime/WorldTimeViewController.swift
  Alarm/Scenes/WorldTime/WorldTime/WorldTimeViewModel.swift
  README.md
Labels: feat
